### ISSUE TITLE
Can you (or how do you) specify only one of the custom prompts defined

### ISSUE THREAD

**Issue by kostecky** [MaurerKrisztian/issue-improver-action#6]
Can we specify only one of the custom responses we may define in the config file? Right now 'add-custom-section' appears to execute them all.

**Comment by MaurerKrisztian** [comment]
Done. You can pick the custom section you want by separating it with a comma in "add-custom-section". Or, choose them all by using the "*" symbol. You can use `id` or `title` field.

e.g.

```json
	"sections": {
		"custom": [
			{
				"title": "Joke",
				"prompt": "make a joke about this: {{issueTitle}}"
			},
			{
				"id":"poem",
				"title": "Poem Title",
				"prompt": "Write a short poem about this: {{issueTitle}}"
			}
		],
}
```

![image](https://user-images.githubusercontent.com/48491140/237036181-773ad80e-26e2-421e-bc0f-9ed0e2d519b6.png)

![image](https://user-images.githubusercontent.com/48491140/237036064-d1d7226e-ff36-48ad-9b5b-27fe1fc17c56.png)

**Comment by kostecky** [comment]
This is great, thank you!
