### ISSUE TITLE
Allow usage for gpt-4 model

### ISSUE THREAD

**Issue by kostecky** [MaurerKrisztian/issue-improver-action#7]
A possible enhancement could be to allow for gpt4 to be used. I tried specifying it as 'gpt4' and 'gpt-4', but it does not work. I assume it's because it needs to use the `chatCompletion` endpoint vs. `createCompletion`.

**Comment by MaurerKrisztian** [comment]
Yes, you are right. It has 2 endpoints with different models. Good idea. 
https://platform.openai.com/docs/models/model-endpoint-compatibility

**Comment by lduf** [comment]
Any update here ?

**Comment by MaurerKrisztian** [comment]
@lduf  I plan to make the necessary changes to this soon.  Btw feel free to open a PR.

**Comment by MaurerKrisztian** [comment]
@lduf Done, GPT-4 now is available. To try out the latest features before the official release, use the `latest` flag: `MaurerKrisztian/issue-improver-action@latest`. You can specify the model input in the action but the default now is gpt-4.

## Improvements
- **Updated OpenAI Library:** Upgraded to the latest version of the OpenAI npm library, which includes API changes.
- **Endpoint Change:** Transitioned from the legacy `/v1/completions` endpoint to the new `/v1/chat/completions`. For more details, see the [Model Endpoint Compatibility documentation](https://platform.openai.com/docs/models/model-endpoint-compatibility).
- **Configuration Options:** Introduced an option in the configuration for system messages.
- **Code Refactoring:** Eliminated redundant code for better efficiency and maintainability.

## Pending Tasks (before release)
- **Update README:**  Modify README.md to reflect the latest changes. (`systemMessage` new config option, default model..)
- **Test:** Test the current features

**Comment by MaurerKrisztian** [comment]
Done, new version v1.1 has been released.
